name: ticker
description: "A realtime price ticker"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  data_layer:
    path: ./data_layer
  domain_layer:
    path: ./domain_layer

  get_it: ^8.0.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  flutter_lints: ^4.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
