name: data_layer
description: "A data layer for the app can be used to interact with the database, network, and other data sources."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  domain_layer:
    path: ../domain_layer

  http: ^1.2.2
  web_socket_channel: ^2.4.5
  shared_preferences: ^2.2.3
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_lints: ^4.0.0
  test: ^1.25.0
  mockito: ^5.4.4
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1